// Generated by Glide — https://glidelang.dev
// Do not edit manually.

if (!window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
  gsap.from(".hero", {
    opacity: 0,
    y: 50,
    duration: 0.8,
    ease: "power2.out",
    delay: 0.2
  });

  gsap.from(".about", {
    opacity: 0,
    y: 50,
    duration: 0.6,
    ease: "power2.out",
    scrollTrigger: { trigger: ".about", start: "top 80%", toggleActions: "play none none none" }
  });

  gsap.from(".parallax-bg", {
    y: -100,
    duration: 0.6,
    ease: "power2.out",
    scrollTrigger: { trigger: ".parallax-bg", start: "top bottom", scrub: true, end: "bottom top" }
  });

  document.querySelectorAll(".button").forEach(el => {
    el.addEventListener("mouseenter", () => gsap.to(el, {
      scale: 1.08,
      duration: 0.25,
      ease: "back.out(1.7)"
    }));
    el.addEventListener("mouseleave", () => gsap.to(el, {
      duration: 0.25,
      scale: 1
    }));
  });

  document.querySelectorAll(".menu-icon").forEach(el => {
    el.addEventListener("click", () => gsap.to(el, {
      rotation: 45,
      duration: 0.3,
      ease: "power2.out"
    }));
  });

  gsap.from(".cards", {
    opacity: 0,
    y: 50,
    duration: 0.6,
    ease: "power2.out",
    stagger: { each: 0.12, from: "start" }
  });

  gsap.from(".custom", {
    opacity: 0,
    x: -200,
    duration: 0.8,
    ease: "power2.out"
  });

  const pageLoad = gsap.timeline();
  pageLoad.from(".logo", {
    opacity: 0,
    duration: 0.6,
    ease: "power2.out"
  }, ">");
  pageLoad.from(".navbar", {
    y: -60,
    duration: 0.6,
    ease: "power2.out"
  }, 0.3);
  pageLoad.from(".headline", {
    opacity: 0,
    y: 50,
    duration: 1,
    ease: "power2.out"
  }, ">");
  pageLoad.from(".cta", {
    opacity: 0,
    scale: 0,
    duration: 0.6,
    ease: "bounce.out"
  }, ">");

}