// Generated by Glide — https://glidelang.dev
// Do not edit manually.

if (!window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
  gsap.from(".empty-entrance", {
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.to(".empty-exit", {
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  document.querySelectorAll(".empty-hover").forEach(el => {
    el.addEventListener("mouseenter", () => gsap.to(el, {
      duration: 0.35,
      ease: "elastic.out(1, 0.3)"
    }));
    el.addEventListener("mouseleave", () => gsap.to(el, {
      duration: 0.35
    }));
  });

  document.querySelectorAll(".empty-click").forEach(el => {
    el.addEventListener("click", () => gsap.to(el, {
      duration: 0.35,
      ease: "elastic.out(1, 0.3)"
    }));
  });

  gsap.from(".empty-scroll", {
    duration: 0.35,
    ease: "elastic.out(1, 0.3)",
    scrollTrigger: { trigger: ".empty-scroll", start: "top 80%", toggleActions: "play none none none" }
  });

  gsap.from(".ease-smooth", {
    opacity: 0,
    duration: 0.5,
    ease: "power2.out"
  });

  gsap.from(".ease-snap", {
    opacity: 0,
    duration: 0.5,
    ease: "power4.out"
  });

  gsap.from(".ease-bounce", {
    opacity: 0,
    duration: 0.5,
    ease: "bounce.out"
  });

  gsap.from(".ease-elastic", {
    opacity: 0,
    duration: 0.5,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".ease-back", {
    opacity: 0,
    duration: 0.5,
    ease: "back.out(1.7)"
  });

  gsap.from(".ease-linear", {
    opacity: 0,
    duration: 0.5,
    ease: "none"
  });

  gsap.from(".preset-fade", {
    opacity: 0,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".preset-fadeUp", {
    opacity: 0,
    y: 50,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".preset-fadeDown", {
    opacity: 0,
    y: -50,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".preset-fadeLeft", {
    opacity: 0,
    x: 50,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".preset-fadeRight", {
    opacity: 0,
    x: -50,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".preset-zoomIn", {
    opacity: 0,
    scale: 0.8,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".preset-popIn", {
    opacity: 0,
    scale: 0,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".preset-slideUp", {
    y: 60,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".preset-slideDown", {
    y: -60,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".unknown-effect", {
    duration: 0.6,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.to(".unknown-loop", {
    duration: 1,
    ease: "elastic.out(1, 0.3)",
    repeat: -1
  });

  // 3d effect "hologram" not recognized

  gsap.from(".negative-x", {
    x: -100,
    y: -50,
    opacity: 0,
    duration: 0.6,
    ease: "elastic.out(1, 0.3)"
  });

  gsap.from(".negative-parallax", {
    y: -200,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)",
    scrollTrigger: { trigger: ".negative-parallax", start: "top bottom", scrub: true }
  });

  gsap.from(".decimal-duration", {
    opacity: 0,
    y: 50,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)",
    delay: 0.05
  });

  gsap.from(".decimal-stagger", {
    opacity: 0,
    y: 50,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)",
    stagger: { each: 0.05 }
  });

  gsap.from(".props-combo", {
    opacity: 0,
    x: -100,
    y: -50,
    scale: 0.9,
    duration: 0.8,
    ease: "back.out(1.7)",
    delay: 0.15
  });

  gsap.to(".props-exit-combo", {
    opacity: 0,
    y: 30,
    duration: 0.4,
    ease: "power2.out"
  });

  gsap.from(".items", {
    opacity: 0,
    y: 50,
    duration: 0.6,
    ease: "back.out(1.7)",
    stagger: { each: 0.08, from: "center" }
  });

  document.querySelectorAll(".card-hover").forEach(el => {
    el.addEventListener("mouseenter", () => gsap.to(el, {
      x: -5,
      y: -5,
      scale: 1.05,
      duration: 0.25,
      ease: "back.out(1.7)"
    }));
    el.addEventListener("mouseleave", () => gsap.to(el, {
      duration: 0.25,
      x: 0,
      y: 0,
      scale: 1
    }));
  });

  document.querySelectorAll(".btn-click").forEach(el => {
    el.addEventListener("click", () => gsap.to(el, {
      scale: 0.95,
      opacity: 0.8,
      duration: 0.15,
      ease: "none"
    }));
  });

  gsap.from(".full-scroll", {
    opacity: 0,
    y: 50,
    duration: 0.7,
    ease: "power2.out",
    scrollTrigger: { trigger: ".full-scroll", start: "top 75%", toggleActions: "play none none none" }
  });

  gsap.from(".scrub-full", {
    y: -150,
    duration: 0.35,
    ease: "elastic.out(1, 0.3)",
    scrollTrigger: { trigger: ".scrub-full", start: "top bottom", scrub: true, end: "bottom top" }
  });

}