// Generated by Glide — https://glidelang.dev
// Do not edit manually.

if (!window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
  gsap.registerPlugin(TextPlugin, SplitText, MorphSVGPlugin);

  gsap.from(".hero", {
    opacity: 0,
    y: 50,
    duration: 0.8,
    ease: "power2.out",
    delay: 0.2
  });

  gsap.from(".intro", {
    opacity: 0,
    scale: 0.8,
    duration: 1,
    ease: "back.out(1.7)"
  });

  gsap.to(".modal", {
    opacity: 0,
    duration: 0.4,
    ease: "power2.out"
  });

  gsap.to(".banner", {
    y: 60,
    opacity: 0,
    duration: 0.5,
    ease: "power2.out"
  });

  gsap.from(".section", {
    opacity: 0,
    y: 50,
    duration: 0.8,
    ease: "power2.out",
    scrollTrigger: { trigger: ".section", start: "top 80%", toggleActions: "play none none none" }
  });

  gsap.from(".parallax", {
    y: -150,
    duration: 0.6,
    ease: "power2.out",
    scrollTrigger: { trigger: ".parallax", start: "top bottom", scrub: true, end: "bottom top" }
  });

  document.querySelectorAll(".card").forEach(el => {
    el.addEventListener("mouseenter", () => gsap.to(el, {
      scale: 1.05,
      duration: 0.3,
      ease: "back.out(1.7)"
    }));
    el.addEventListener("mouseleave", () => gsap.to(el, {
      duration: 0.3,
      scale: 1
    }));
  });

  document.querySelectorAll(".nav-link").forEach(el => {
    el.addEventListener("mouseenter", () => gsap.to(el, {
      opacity: 0.7,
      duration: 0.2,
      ease: "power2.out"
    }));
    el.addEventListener("mouseleave", () => gsap.to(el, {
      duration: 0.2,
      opacity: 1
    }));
  });

  document.querySelectorAll(".burger").forEach(el => {
    el.addEventListener("click", () => gsap.to(el, {
      rotation: 45,
      duration: 0.3,
      ease: "power2.out"
    }));
  });

  document.querySelectorAll(".toggle").forEach(el => {
    el.addEventListener("click", () => gsap.to(el, {
      scale: 0.95,
      duration: 0.15,
      ease: "power2.out"
    }));
  });

  gsap.from(".grid-item", {
    opacity: 0,
    y: 50,
    duration: 0.6,
    ease: "power2.out",
    stagger: { each: 0.1, from: "start" }
  });

  gsap.from(".list-item", {
    y: 60,
    duration: 0.6,
    ease: "power2.out",
    stagger: { each: 0.08 }
  });

  {
    const _el = document.querySelector(".title");
    const _text = _el.textContent;
    _el.textContent = "";
    gsap.to(_el, { duration: 2, text: _text, ease: "none" });
  }

  gsap.from(".subtitle", {
    duration: 0.8,
    clipPath: "inset(0 100% 0 0)",
    ease: "power2.out"
  });

  const _split__chars = new SplitText(".chars", { type: "chars" });
  gsap.from(_split__chars.chars, {
    duration: 0.6,
    opacity: 0,
    y: 20,
    stagger: { each: 0.05 },
    ease: "back.out(1.7)"
  });

  const _split__words = new SplitText(".words", { type: "words" });
  gsap.from(_split__words.words, {
    duration: 0.6,
    opacity: 0,
    y: 20,
    stagger: { each: 0.08 },
    ease: "power2.out"
  });

  {
    const _el = document.querySelector(".logo-path");
    const _len = _el.getTotalLength();
    gsap.fromTo(_el,
      { strokeDashoffset: _len, strokeDasharray: _len },
      { strokeDashoffset: 0, duration: 1.5, ease: "power2.out" }
    );
  }

  {
    const _el = document.querySelector(".logo-delayed");
    const _len = _el.getTotalLength();
    gsap.fromTo(_el,
      { strokeDashoffset: _len, strokeDasharray: _len },
      { strokeDashoffset: 0, duration: 2, ease: "power2.out", delay: 0.5 }
    );
  }

  gsap.to(".blob", {
    morphSVG: "#blob-2",
    duration: 1,
    ease: "power2.out"
  });

  gsap.to(".dashed-line", {
    strokeDashoffset: -100,
    duration: 1.5,
    ease: "none",
    repeat: -1
  });

  gsap.to(".spinner", {
    rotation: 360,
    duration: 1,
    ease: "none",
    repeat: -1
  });

  gsap.to(".pulse-dot", {
    scale: 1.05,
    duration: 1.2,
    ease: "power1.inOut",
    yoyo: true,
    repeat: -1
  });

  gsap.to(".bouncer", {
    y: -20,
    duration: 0.8,
    ease: "bounce.out",
    yoyo: false,
    repeat: -1
  });

  gsap.to(".breathe", {
    scale: 1.1,
    duration: 2,
    ease: "power2.out",
    repeat: -1,
    yoyo: true
  });

  const pageLoad = gsap.timeline();
  pageLoad.from(".logo", {
    opacity: 0,
    duration: 0.6,
    ease: "power2.out"
  }, ">");
  pageLoad.from(".nav", {
    y: -60,
    duration: 0.6,
    ease: "power2.out"
  }, 0.3);
  pageLoad.from(".headline", {
    opacity: 0,
    y: 50,
    duration: 1,
    ease: "power2.out"
  }, ">");
  pageLoad.from(".cta", {
    opacity: 0,
    scale: 0,
    duration: 0.6,
    ease: "bounce.out"
  }, ">");

  gsap.to(".shape-a", {
    morphSVG: "#shape-b",
    duration: 0.8,
    ease: "power2.out"
  });

  gsap.to(".ball", {
    y: 300,
    duration: 0.183,
    ease: "elastic.out(1, 0.08)"
  });

  gsap.to(".elastic-box", {
    scale: 1.2,
    duration: 0.173,
    ease: "elastic.out(1, 0.2)"
  });

  gsap.to(".panel", {
    x: 400,
    duration: 0.224,
    ease: "elastic.out(1, 0.12)"
  });

  window.addEventListener("mousemove", (e) => {
    gsap.to(".custom-cursor", { x: e.clientX, y: e.clientY, duration: 0.1, ease: "power2.out" });
  });

  document.querySelectorAll(".cta-btn").forEach(el => {
    el.addEventListener("mouseenter", (e) => {
      const r = el.getBoundingClientRect();
      const offsetX = e.clientX - (r.left + r.width  / 2);
      const offsetY = e.clientY - (r.top  + r.height / 2);
      gsap.to(".cursor-dot", { x: offsetX * 0.4, y: offsetY * 0.4, ease: "power2.out" });
    });
    el.addEventListener("mouseleave", () => {
      gsap.to(".cursor-dot", { x: 0, y: 0, ease: "power2.out" });
    });
  });

  {
    const _dots = document.querySelectorAll(".trail-dot");
    window.addEventListener("mousemove", (e) => {
      _dots.forEach((dot, i) => {
        gsap.to(dot, { x: e.clientX, y: e.clientY, duration: i * 0.05 + 0.1, ease: "none" });
      });
    });
  }

  document.querySelector(".flip-card").parentElement.style.perspective = "1000px";
  gsap.to(".flip-card", {
    rotationY: 180,
    duration: 0.6,
    ease: "power2.out"
  });

  gsap.to(".cube", {
    rotationX: 30,
    rotationY: 60,
    duration: 1,
    ease: "power2.out"
  });

  document.querySelectorAll(".product-card").forEach(el => {
    el.addEventListener("mousemove", (e) => {
      const r = el.getBoundingClientRect();
      const normX =  (e.clientX - r.left)  / r.width  - 0.5;
      const normY =  (e.clientY - r.top)   / r.height - 0.5;
      gsap.to(el, { rotationY: normX * 15, rotationX: -normY * 15, ease: "power2.out" });
    });
    el.addEventListener("mouseleave", () => {
      gsap.to(el, { rotationX: 0, rotationY: 0, ease: "power2.out" });
    });
  });

  gsap.to(".scene", {
    z: -300,
    duration: 0.8,
    ease: "power2.out"
  });

  (function initPageTransitions() {
    let overlay = document.getElementById("glide-overlay");
    if (!overlay) {
      overlay = document.createElement("div");
      overlay.id = "glide-overlay";
      Object.assign(overlay.style, {
        position: "fixed", top: "0", left: "0", width: "100%", height: "100%",
        background: "#000", zIndex: "9999", pointerEvents: "none",
      });
      document.body.appendChild(overlay);
    }

    gsap.set(overlay, { scaleY: 0 });
    function enterAnim(onComplete) {
      gsap.fromTo(overlay, { scaleY: 0, transformOrigin: "top" }, { scaleY: 1, duration: 0.6, ease: "power4.out", onComplete });
    }
    function exitAnim() {
      gsap.fromTo(overlay, { scaleY: 1, transformOrigin: "bottom" }, { scaleY: 0, duration: 0.6, ease: "power4.out" });
    }

    document.addEventListener("click", (e) => {
      const a = e.target.closest("a");
      if (!a) return;
      const href = a.getAttribute("href");
      if (!href || a.target === "_blank" || /^[a-z][a-z0-9+.-]*:/i.test(href)) return;
      e.preventDefault();
      enterAnim(() => { window.location.href = href; });
    });

    window.addEventListener("pageshow", () => exitAnim());
  })();

}